spring:
  application:
    name: employees
  datasource:
    url: jdbc:mysql://localhost:3306/employees?createDatabaseIfNotExist=true
    username: #<-- ADD YOUR DB USERNAME
    password: #<-- ADD YOUR DB PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
